import Head from 'next/head';

import { Product, FooterBanner, HeroBanner } from '../components';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;600&display=swap" rel="stylesheet" />
      </Head>
      <div>
        <HeroBanner />
        <div className='product-heading'>
          <h1>Best Selling Accessories</h1>
          <p>Good Headphones</p>
        </div>
        <div className='product-container'>
          {['product1', 'product2'].map((product) => product)}
        </div>
        <FooterBanner />
      </div>
    </>
  )
}
