import Head from 'next/head';
import  client  from '../lib/client';

import { Product, FooterBanner, HeroBanner } from '../components';


export default function Home({products, bannerData}) {
  return (
    <>
      <Head>
        <title>Tech | Temple</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;600&display=swap" rel="stylesheet" />
      </Head>
      <div>
        <HeroBanner />
        {console.log(bannerData)}
        <div className='product-heading'>
          <h1>Best Selling Accessories</h1>
          <p>Good Headphones</p>
        </div>
        <div className='product-container'>
          {products?.map((product) => product.name)}
        </div>
        <FooterBanner />
      </div>
    </>
  )
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);
  
  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: {products , bannerData}
  }
}
